package com.mawelly.blitzmath.game

import com.mawelly.blitzmath.localization.AppLanguage

data class MathQuote(
    val quoteTR: String,
    val quoteEN: String,
    val quoteES: String,
    val quoteDE: String,
    val quoteFR: String,
    val quoteIT: String,
    val quotePT: String,
    val quoteHI: String,
    val quoteZH: String,
    val quoteRU: String,
    val author: String
) {
    fun getQuote(language: AppLanguage): String {
        return when (language) {
            AppLanguage.TURKISH -> quoteTR
            AppLanguage.ENGLISH -> quoteEN
            AppLanguage.SPANISH -> quoteES
            AppLanguage.GERMAN -> quoteDE
            AppLanguage.FRENCH -> quoteFR
            AppLanguage.ITALIAN -> quoteIT
            AppLanguage.PORTUGUESE -> quotePT
            AppLanguage.HINDI -> quoteHI
            AppLanguage.CHINESE -> quoteZH
            AppLanguage.RUSSIAN -> quoteRU
        }
    }
}

val mathQuotes = listOf(
    MathQuote("Hayatta en hakiki mürşit ilimdir, fendir.", "The truest guide in life is science, knowledge.", "La guía más verdadera en la vida es la ciencia.", "Der wahrste Führer im Leben ist die Wissenschaft.", "Le guide le plus vrai dans la vie est la science.", "La vera guida nella vita è la scienza.", "O guia mais verdadeiro na vida é a ciência.", "जीवन में सबसे सच्चा मार्गदर्शक विज्ञान है।", "生命中最真实的指引是科学。", "Самый верный наставник в жизни — это наука, знания.", "M. Kemal Atatürk"),
    MathQuote("Matematik zaten her zaman vardı, insanoğlu sadece onu buldu.", "Mathematics has always existed; humanity merely discovered it.", "Las matemáticas siempre han existido; la humanidad simplemente las descubrió.", "Die Mathematik hat immer existiert; die Menschheit hat sie lediglich entdeckt.", "Les mathématiques ont toujours existé ; l'humanité n'a fait que les découvrir.", "La matematica è sempre esistita; l'umanità l'ha solo scoperta.", "A matemática sempre existiu; a humanidade apenas a descobriu.", "गणित हमेशा मौजूद रहा है; मानवता ने केवल इसकी खोज की।", "数学一直存在；人类只是发现了它。", "Математика существовала всегда, человечество лишь открыло её.", "Cahit Arf"),
    MathQuote("Matematik, doğanın gizli düzenini ortaya çıkarır.", "Mathematics reveals the hidden order of nature.", "Las matemáticas revelan el orden oculto de la naturaleza.", "Mathematik offenbart die verborgene Ordnung der Natur.", "Les mathématiques révèlent l'ordre caché de la nature.", "La matematica rivela l'ordine nascosto della natura.", "A matemática revela a ordem oculta da natureza.", "गणित प्रकृति के छिпе हुए क्रम को प्रकट करता है।", "数学揭示了自然界隐藏的秩序。", "Математика раскрывает скрытый порядок природы.", "Galileo Galilei"),
    MathQuote("Matematik, bilimlerin annesi ve mantığın kraliçesidir.", "Mathematics is the queen of sciences and the queen of logic.", "Las matemáticas son la reina de las ciencias y la reina de la lógica.", "Die Mathematik ist die Königin der Wissenschaften und die Königin der Logik.", "Les mathématiques sont la reine des sciences et la reine de la logique.", "La matematica è la regina delle scienze e la regina della logica.", "A matemática é a rainha das ciências e a rainha da lógica.", "गणित विज्ञान की रानी और तर्क की रानी है।", "数学是科学的女王，也是逻辑的女王。", "Математика — царица наук и царица логики.", "Carl Friedrich Gauss"),
    MathQuote("Matematik, akıl ve mantığın muhteşem birlikteliğidir.", "Mathematics is the magnificent union of mind and logic.", "Las matemáticas son la magnífica unión de mente y lógica.", "Mathematik ist die großartige Vereinigung von Verstand und Logik.", "Les mathématiques sont la magnifique union de l'esprit et de la logique.", "La matematica è la magnifica unione di mente e logica.", "A matemática é a magnífica união da mente e da lógica.", "गणित मन और तर्क का शानदार मिलन है।", "数学是头脑与逻辑的壮丽结合。", "Математика — это великолепный союз разума и логики.", "Albert Einstein"),
    MathQuote("Matematik, kaosun içindeki düzeni görmemizi sağlar.", "Mathematics allows us to see order within chaos.", "Las matemáticas nos permiten ver el orden dentro del caos.", "Mathematik erlaubt es uns, Ordnung im Chaos zu sehen.", "Les mathématiques nous permettent de voir l'ordre dans le chaos.", "La matematica ci permette di vedere l'ordine nel caos.", "A matemática nos permite ver a ordem dentro do caos.", "गणित हमें अराजकता के भीतर क्रम देखने की अनुमति देता है।", "数学让我们 в混沌中看到秩序。", "Математика позволяет нам видеть порядок в хаосе.", "Edward Kasner"),
    MathQuote("Matematikte güzellik yoktur, güzellik matematiktir.", "There is no beauty in mathematics; beauty is mathematics.", "No hay belleza en las matemáticas; la belleza son las matemáticas.", "Es gibt keine Schönheit in der Mathematik; die Schönheit ist die Mathematik.", "Il n'y a pas de beauté en mathématiques ; la beauté, ce sont les mathématiques.", "Non c'è bellezza nella matematica; la bellezza è la matematica.", "Não há beleza na matemática; a beleza é a matemática.", "गणित में कोई सुंदरता नहीं है; सुंदरता ही गणित है।", "数学本身没有美；美就是数学。", "В математике нет красоты, красота — это и есть математика.", "Henri Poincaré"),
    MathQuote("Matematik, gerçeğin en kesin ifadesidir.", "Mathematics is the most precise expression of truth.", "Las matemáticas son la expresión más precisa de la verdad.", "Mathematik ist der präziseste Ausdruck der Wahrheit.", "Les mathématiques sont l'expression la plus précise de la vérité.", "La matematica è l'espressione più precisa della verità.", "A matemática é a expressão mais precisa da verdade.", "गणित सत्य की सबसे सटीक अभिव्यक्ति है।", "数学是真理最精确的表达。", "Математика — самое точное выражение истины.", "Leonardo da Vinci"),
    MathQuote("Matematik olmadan gerçek bilgiye ulaşılamaz.", "True knowledge cannot be reached without mathematics.", "No se puede alcanzar el verdadero conocimiento sin las matemáticas.", "Wahres Wissen kann ohne Mathematik nicht erreicht werden.", "La véritable connaissance ne peut être atteinte sans les mathématiques.", "La vera conoscenza non può essere raggiunta senza la matematica.", "O verdadeiro conhecimento não pode ser alcançado sem a matemática.", "गणित के बिना सच्चे ज्ञान तक नहीं पहुँचा जा सकता।", "没有数学就无法获得真正的知识。", "Истинное знание недостижимо без математики.", "Plato"),
    MathQuote("Sayılar, evrenin temel yapı taşlarıdır.", "Numbers are the fundamental building blocks of the universe.", "Los números son los bloques de construcción fundamentales del universo.", "Zahlen sind die fundamentalen Bausteine des Universums.", "Les nombres sont les éléments fondamentaux de l'univers.", "I numeri sono i mattoni fondamentali dell'universo.", "Os números son os blocos de construção fundamentais do universo.", "संख्याएँ ब्रह्मांड के मूल निर्माण खंड हैं।", "数字是宇宙的基本构建块。", "Числа — это фундаментальные строительные блоки вселенной.", "Pythagoras"),
    MathQuote("Matematik, düşüncenin şiiridir.", "Mathematics is the poetry of thought.", "Las matemáticas son la poesía del pensamiento.", "Mathematik ist die Poesie des Denkens.", "Les mathématiques sont la poésie de la pensée.", "La matematica è la poesia del pensamento.", "A matemática é a poesia do pensamento.", "गणित विचार की कविता है।", "数学是思想的诗篇。", "Математика — это поэзия мысли.", "Luitzen Brouwer"),
    MathQuote("Matematik, sonsuzluğun bilimidir.", "Mathematics is the science of infinity.", "Las matemáticas son la ciencia de lo infinito.", "Mathematik ist die Wissenschaft der Unendlichkeit.", "Les mathématiques sont la science de l'infini.", "La matematica è la scienza dell'infinito.", "A matemática é a ciência do infinito.", "गणित अनंत का विज्ञान है।", "数学是无限的科学。", "Математика — наука о бесконечности.", "David Hilbert"),
    MathQuote("Bir problemi çözmek, yeni bir dünya keşfetmektir.", "Solving a problem is discovering a new world.", "Resolver un problema es descubrir un mundo nuevo.", "Ein Problem zu lösen bedeutet, eine neue Welt zu entdecken.", "Résoudre un problème, c'est découvrir un nouveau monde.", "Risolvere un problema è scoprire un nouveau mondo.", "Resolver um problema é descobrir um novo mundo.", "किसी समस्या को हल करना एक नई दुनिया की खोज करना है।", "解决问题就是发现一个新世界。", "Решение задачи — это открытие нового мира.", "Georg Cantor"),
    MathQuote("Matematik, zihnin jimnastiğidir.", "Mathematics is gymnastics for the mind.", "Las matemáticas son gimnasia para la mente.", "Mathematik ist Gymnastik für den Geist.", "Les mathématiques sont la gymnastique de l'esprit.", "La matematica è ginnastica per la mente.", "A matemática é ginástica para a mente.", "गणित मन के लिए व्यायाम है।", "数学是大脑的体操。", "Математика — это гимнастика для ума.", "Isaac Asimov"),
    MathQuote("Matematik, gerçeğin en saf şeklidir.", "Mathematics is the purest form of truth.", "Las matemáticas son la forma más pura de la verdad.", "Mathematik ist die reinste Form der Wahrheit.", "Les mathématiques sont la forme la plus pure de la vérité.", "La matematica è la forma più pura della verità.", "A matemática é a forma mais pura da verdade.", "गणित सत्य का सबसे शुद्ध रूप है।", "数学是真理最纯粹的形式。", "Математика — самая чистая форма истины.", "Bertrand Russell"),
    MathQuote("Matematik, geleceğin anahtarıdır.", "Mathematics is the key to the future.", "Las matemáticas son la clave del futuro.", "Mathematik ist der Schlüssel zur Zukunft.", "Les mathématiques sont la clé de l'avenir.", "La matematica è la chiave per il futuro.", "A matemática é a chave para o futuro.", "गणित भविष्य की कुंजी है।", "数学是通向未来的钥匙。", "Математика — ключ к будущему.", "Ada Lovelace"),
    MathQuote("Her problem, bir fırsattır.", "Every problem is an opportunity.", "Todo problema es una oportunidad.", "Jedes Problem ist eine Gelegenheit.", "Chaque problème est une opportunité.", "Ogni problema è un'opportunità.", "Todo problema é uma oportunidade.", "हर समस्या एक अवसर है।", "每个问题都是一个机会。", "Каждая задача — это возможность.", "George Pólya"),
    MathQuote("Matematik, sabır ve azmin zaferidir.", "Mathematics is the victory of patience and perseverance.", "Las matemáticas son la victoria de la paciencia y la perseverancia.", "Mathematik ist der Sieg von Geduld und Beharrlichkeit.", "Les mathématiques sont la victoire de la patience et de la persévérance.", "La matematica è la vittoria della pazienza e della perseveranza.", "A matemática é a vitória da paciência e da perseverança.", "गणित धैर्य और दृढ़ता की जीत है।", "数学은 인내와 끈기의 승리입니다。", "Математика — это победа терпения и настойчивости.", "Andrew Wiles"),
    MathQuote("Küçük adımlar, büyük keşiflere yol açar.", "Small steps lead to great discoveries.", "Pequeños pasos llevan a grandes descubrimientos.", "Kleine Schritte führen zu großen Entdeckungen.", "De petits pas mènent à de grandes découvertes.", "Piccoli passi portano a grandi scoperte.", "Pequenos passos levam a grandes descobertas.", "छोटे कदम बड़ी खोजों की ओर ले जाते हैं।", "一小步成就大発見。", "Маленькие шаги ведут к великим открытиям.", "Srinivasa Ramanujan"),
    MathQuote("Matematik, mantığın sanat halidir.", "Mathematics is the art of logic.", "Las matemáticas son el arte de la lógica.", "Mathematik ist die Kunst der Logik.", "Les mathématiques sont l'art de la logique.", "La matematica è l'arte della logica.", "A matemática é a arte da lógica.", "गणित तर्क की कला है।", "数学是逻辑的艺术。", "Математика — это искусство логики.", "Marcus du Sautoy"),
    MathQuote("Bir denklem, evrenin bir şifresidir.", "An equation is the code of the universe.", "Una ecuación es el código del universo.", "Eine Gleichung ist der Code des Universums.", "Une équation est le code de l'univers.", "Un'equazione è il codice dell'universo.", "Uma equação é o código do universo.", "एक समीकरण ब्रह्मांड का कोड है।", "一个方程就是宇宙的代码。", "Уравнение — это код вселенной.", "Stephen Hawking"),
    MathQuote("Matematik, hayal gücünün disiplindir.", "Mathematics is the discipline of imagination.", "Las matemáticas son la disciplina de la imaginación.", "Mathematik ist die Disziplin der Fantasie.", "Les mathématiques sont la discipline de l'imagination.", "La matematica è la disciplina dell'immaginazione.", "A matemática é a disciplina da imaginação.", "गणित कल्पना का अनुशासन है।", "数学是想象力的纪律。", "Математика — это дисциплина воображения.", "Alfred North Whitehead"),
    MathQuote("Her çözüm, bir zaferdir.", "Every solution is a victory.", "Toda solución es una victoria.", "Jede Lösung ist ein Sieg.", "Chaque solution est une victoire.", "Ogni soluzione è una vittoria.", "Toda solução é uma vitória.", "हर समाधान एक जीत है।", "每一个解决方案都是一次胜利。", "Каждое решение — это победа.", "John Nash"),
    MathQuote("Matematik, düşüncenin en derin biçimidir.", "Mathematics is the deepest form of thought.", "Las matemáticas son la forma más profunda de pensamiento.", "Mathematik ist die tiefste Form des Denkens.", "Les mathématiques sont la forme la plus profonde de la pensée.", "La matematica è la forma più profonda di pensiero.", "A matemática é a forma mais profunda de pensamento.", "गणित विचार का सबसे गहरा रूप है।", "数学是思想最深刻的形式。", "Математика — самая глубокая форма мысли.", "René Descartes"),
    MathQuote("Bir teorem, sonsuz gerçeklerin özüdür.", "A theorem is the essence of infinite truths.", "Un teorema es la esencia de verdades infinitas.", "Ein Theorem ist die Essenz unendlicher Wahrheiten.", "Un théorème est l'essence de vérités infinies.", "Un teorema è l'essenza di infinite verità.", "Um teorema é a essência de verdades infinitas.", "एक प्रमेय अनंत सत्य का सार है।", "一个定理是无限真理的本质。", "Теорема — это сущность бесконечных истин.", "G.H. Hardy"),
    MathQuote("Matematik, evrenin kullanım kılavuzudur.", "Mathematics is the manual of the universe.", "Las matemáticas son el manual del universo.", "Mathematik ist das Handbuch des Universums.", "Les mathématiques sont le manuel de l'univers.", "La matematica è il manuale dell'universo.", "A matemática é o manual do universo.", "गणित ब्रह्मांड का मैनुअल है।", "数学是宇宙的使用说明书。", "Математика — это инструкция к вселенной.", "Richard Feynman"),
    MathQuote("Sayılar, zamanın ve mekanın ritmidir.", "Numbers are the rhythm of time and space.", "Los números son el ritmo del tiempo y el espacio.", "Zahlen sind der Rhythmus von Zeit und Raum.", "Les nombres sont le rythme du temps et de l'espace.", "I numeri sono il ritmo del tempo e dello spazio.", "Os números são o ritmo do tempo e do espaço.", "संख्याएँ समय और स्थान की लय हैं।", "数字是时空的节奏。", "Числа — это ритм времени и пространства.", "Isaac Newton"),
    MathQuote("Matematik, sabrın sanatıdır.", "Mathematics is the art of patience.", "Las matemáticas son el arte de la paciencia.", "Mathematik ist die Kunst der Geduld.", "Les mathématiques sont l'art de la patience.", "La matematica è l'arte della pazienza.", "A matemática é a arte da paciência.", "गणित धैर्य की कला है।", "数学은 인내의 예술입니다。", "Математика — это искусство терпения.", "Pierre de Fermat"),
    MathQuote("Her problem, bir kapıdır; çözüm ise anahtar.", "Every problem is a door; the solution is the key.", "Todo problema es una puerta; la solución es la llave.", "Jedes Problem ist eine Tür; die Lösung ist der Schlüssel.", "Chaque problème est une porte ; la solution est la clé.", "Ogni problema è una porta; la soluzione è la chiave.", "Todo problema é uma porta; a solução é a chave.", "हर समस्या एक दरवाजा है; समाधान कुंजी है।", "每个问题都是一扇门；解决方案就是钥匙。", "Каждая задача — это дверь, а решение — ключ к ней.", "Archimedes"),
    MathQuote("Matematik, zihnin sınırlarını zorlar.", "Mathematics pushes the limits of the mind.", "Las matemáticas empujan los límites de la mente.", "Mathematik verschiebt die Grenzen des Verstandes.", "Les mathématiques repoussent les limites de l'esprit.", "La matematica spinge i limiti della mente.", "A matemática ultrapassa os limites da mente.", "गणित मन की सीमाओं को धकेलता है।", "数学挑战思维的极限。", "Математика расширяет границы разума.", "Emmy Noether"),
    MathQuote("Her çözüm, yeni bir maceranın başlangıcıdır.", "Every solution is the beginning of a new adventure.", "Toda solución es el comienzo de una nueva aventura.", "Jede Lösung ist der Beginn eines neuen Abenteuers.", "Chaque solution est le début d'une nouvelle aventure.", "Ogni soluzione è l'inizio di una nuova avventura.", "Toda solução é o começo de uma nova aventura.", "हर समाधान एक नए रोमांच की शुरुआत है।", "每个解决方案都是一次新冒险的开始。", "Каждое решение — это начало нового приключения.", "Blaise Pascal"),
    MathQuote("Matematik, aklın ışığıdır.", "Mathematics is the light of the mind.", "Las matemáticas son la luz de la mente.", "Mathematik ist das Licht des Verstandes.", "Les mathématiques sont la lumière de l'esprit.", "La matematica è la luce della mente.", "A matemática é a luz da mente.", "गणित मन का प्रकाश है।", "数学是头脑的光芒。", "Математика — это свет разума.", "Hypatia"),
    MathQuote("Matematik, gerçeğin en kesin ifadesidir.", "Mathematics is the most precise expression of truth.", "Las matemáticas son la expresión más precisa de la verdad.", "Mathematik ist der präziseste Ausdruck der Wahrheit.", "Les mathématiques sont l'expression la plus précise de la vérité.", "La matematica è l'espressione più precisa della verità.", "A matemática é a expressão mais precisa da verdade.", "गणित सत्य की सबसे सटीक अभिव्यक्ति है।", "数学是真理最精确的表达。", "Математика — самое точное выражение истины.", "Euclid"),
    MathQuote("Sayılar, doğanın gizli kodudur.", "Numbers are the hidden code of nature.", "Los números son el código oculto de la naturaleza.", "Zahlen sind der verborgene Code der Natur.", "Les nombres sont le code caché de la nature.", "I numeri sono il codice nascosto della natura.", "Os números são o código oculto da natureza.", "संख्याएँ प्रकृति का छिपा हुआ कोड हैं।", "数字是自然界的隐藏代码。", "Числа — это скрытый код природы.", "Alan Turing"),
    MathQuote("Matematik, geleceği şekillendiren güçtür.", "Mathematics is the power that shapes the future.", "Las matemáticas son el poder que moldea el futuro.", "Mathematik ist die Kraft, die die Zukunft formt.", "Les mathématiques sont le pouvoir qui façonne l'avenir.", "La matematica è il potere che plasma il futuro.", "A matemática é o poder que molda o futuro.", "गणित वह शक्ति है जो भविष्य को आकार देती है।", "数学是塑造未来的力量。", "Математика — это сила, формирующая будущее.", "John von Neumann"),
    MathQuote("Bir problem, bir fırsattır.", "A problem is an opportunity.", "Un problema es una oportunidad.", "Ein Problem ist eine Gelegenheit.", "Un problème est une opportunité.", "Un problema è un'opportunità.", "Um problema é uma oportunidade.", "एक समस्या एक अवसर है।", "出现问题도 기회입니다。", "Задача — это возможность.", "Paul Erdős"),
    MathQuote("Matematik, düşüncenin en yüksek biçimidir.", "Mathematics is the highest form of thought.", "Las matemáticas son la forma más elevada de pensamiento.", "Mathematik ist die höchste Form des Denkens.", "Les mathématiques sont la forme la plus élevée de la pensée.", "La matematica è la più alta forma di pensiero.", "A matemática é a forma mais elevada de pensamento.", "गणित विचार का सर्वोच्च रूप है।", "数学是思维的最高形式。", "Математика — это высшая форма мысли.", "Aristotle"),
    MathQuote("Matematik, keşfedilmeyi bekleyen bir okyanustur.", "Mathematics is an ocean waiting to be discovered.", "Las matemáticas son un océano esperando ser descubierto.", "Mathematik ist ein Ozean, der darauf wartet, entdeckt zu werden.", "Les mathématiques sont un océan qui attend d'être descubierto.", "La matematica è un oceano in attesa di essere scoperto.", "A matemática é um oceano esperando para ser descoberto.", "गणित एक महासागर है जिसे खोजा जाना बाकी है।", "数学是一片等待被发现的海洋。", "Математика — это океан, ждущий своего открытия.", "Maryam Mirzakhani"),
    MathQuote("Sayılar, evrenin DNA'sıdır.", "Numbers are the DNA of the universe.", "Los números son el ADN del universo.", "Zahlen sind die DNA des Universums.", "Les nombres sont l'DNA de l'universo.", "I numeri sono il DNA dell'universo.", "Os números sono o DNA do universo.", "संख्याएँ ब्रह्मांड का डीएनए हैं।", "数字是宇宙的DNA。", "Числа — это ДНК вселенной.", "Max Tegmark"),
    MathQuote("Matematik, gerçeğin aynasıdır.", "Mathematics is the mirror of truth.", "Las matemáticas son el espejo de la verdad.", "Mathematik ist der Spiegel der Wahrheit.", "Les mathématiques sont le miroir de la vérité.", "La matematica è lo specchio della verità.", "A matemática é o espelho da verdade.", "गणित सत्य का दर्पण है।", "数学是真理的镜子。", "Математика — зеркало истины.", "Roger Bacon"),
    MathQuote("Her zor problem, basit bir çözüm barındırır.", "Every difficult problem contains a simple solution.", "Todo problema difícil contiene una solución simple.", "Jedes schwierige Problem enthält eine einfache Lösung.", "Tout problème difficile contient une solution simple.", "Ogni problema difficile contiene una soluzione semplice.", "Todo problema difícil contém uma solução simples.", "हर कठिन समस्या में एक सरल समाधान होता है।", "每个困难的问题都包含一个简单的解决方案。", "Каждая трудная задача содержит простое решение.", "Leonhard Euler"),
    MathQuote("Matematik, insan aklının en büyük başarısıdır.", "Mathematics is the greatest achievement of the human mind.", "Las matemáticas son el mayor logro de la mente humana.", "Mathematik ist die größte Errungenschaft des menschlichen Geistes.", "Les mathématiques sont la plus grande réussite de l'esprit humain.", "La matematica è il più grande risultato della mente umana.", "A matemática é a maior conquista da mente humana.", "गणित मानव मन की सबसे बड़ी उपलब्धि है।", "数学是人类思维最伟大的成就。", "Математика — величайшее достижение человеческого разума.", "Eugene Wigner"),
    MathQuote("Bir formül, bin kelimeden daha fazlasını anlatır.", "A formula tells more than a thousand words.", "Una fórmula cuenta más que mil palabras.", "Eine Formel sagt mehr als tausend Worte.", "Une formule en dit plus que mille mots.", "Una formula dice più di mille parole.", "Uma fórmula diz mais do que mil palavras.", "एक सूत्र हज़ार शब्दों से भी ज़्यादा कुछ बताता है।", "一个公式胜过千言万语。", "Формула говорит больше, чем тысяча слов.", "Paul Dirac"),
    MathQuote("Matematik, evrenin kalbindedir.", "Mathematics is at the heart of the universe.", "Las matemáticas están en el corazón del universo.", "Mathematik ist das Herzstück des Universums.", "Les mathématiques sont au cœur de l'univers.", "La matematica è al centro dell'universo.", "A matemática está no coração do universo.", "गणित ब्रह्मांड के हृदय में है।", "数学在宇宙的中心。", "Математика находится в самом сердце вселенной.", "Carl Sagan"),
    MathQuote("Her başarısızlık, başarıya giden yolda bir adımdır.", "Every failure is a step on the road to success.", "Cada fracaso es un paso en el camino hacia el éxito.", "Jeder Misserfolg ist ein Schritt auf dem Weg zum Erfolg.", "Chaque échec est une étape sur la voie du succès.", "Ogni fallimento è un passo sulla strada del successo.", "Cada fracasso é um passo no caminho para o sucesso.", "हर विफलता सफलता की राह पर एक कदम है।", "每一次失败都是通往成功之路的一步。", "Каждая неудача — это шаг на пути к успеху.", "Thomas Edison"),
    MathQuote("Matematik, mantığın şiiridir.", "Mathematics is the poetry of logic.", "Las matemáticas son la poesía de la lógica.", "Mathematik ist die Poesie der Logik.", "Les mathématiques sont la poésie de la logique.", "La matematica è la poesia della logica.", "A matemática é a poesia da lógica.", "गणित तर्क की कविता है।", "数学是逻辑的诗歌。", "Математика — это поэзия логики.", "Sofia Kovalevskaya"),
    MathQuote("Matematik, sabır ve tutku işidir.", "Mathematics is a matter of patience and passion.", "Las matemáticas son cuestión de paciencia y pasión.", "Mathematik ist eine Frage von Geduld und Leidenschaft.", "Les mathématiques sont une question de patience et de passion.", "La matematica è una questione di pazienza e passione.", "A matemática é uma questão de paciência e paixão.", "गणित धैर्य और जुनून का मामला है।", "数学은 인내와 열정의 산물입니다。", "Математика — это вопрос терпения и страсти.", "Grigori Perelman"),
    MathQuote("Matematik, evrenin dilidir.", "Mathematics is the language of the universe.", "Las matemáticas son el idioma del universo.", "Mathematik ist the Sprache des Universums.", "Les mathématiques sont la langue de l'univers.", "La matematica è il linguaggio dell'universo.", "A matemática é a linguagem do universo.", "गणित ब्रह्मांड की भाषा है।", "数学是宇宙的语言。", "Математика — это язык вселенной.", "Galileo Galilei"),
    MathQuote("Sayılar, doğanın müziğidir.", "Numbers are the music of nature.", "Los números son la música de la naturaleza.", "Zahlen sind die Musik der Natur.", "Les nombres sont la musique de la nature.", "I numeri sono la musica della natura.", "Os números são a música da natureza.", "संख्याएँ प्रकृति का संगीत हैं।", "数字是自然界的音乐。", "Числа — это музыка природы.", "Pythagoras")
)
